function createfigure(X1, ymatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  stairs x
%  YMATRIX1:  stairs matrix data

%  Auto-generated by MATLAB on 12-Feb-2018 09:30:21

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to stairs
stairs1 = stairs(X1,ymatrix1);
set(stairs1(1),'DisplayName','sinusoida');
set(stairs1(2),'DisplayName','kosinusoida','LineWidth',3,'LineStyle',':',...
    'Color',[0.749019622802734 0 0.749019622802734]);

% Create text
text('Parent',axes1,'VerticalAlignment','baseline',...
    'String','\leftarrow sinusoida',...
    'Position',[0.348101265822785 0.278443113772455 0]);

% Create text
text('Parent',axes1,'VerticalAlignment','baseline','String','x_m',...
    'Position',[0.229166666666667 -0.559880239520958 0]);

% Create text
text('Parent',axes1,'VerticalAlignment','baseline','String','x^2',...
    'Position',[0.51593137254902 -0.284431137724551 0]);

% Create xlabel
xlabel('\Omega');

% Create title
title('Mans grafiks');

% Create ylabel
ylabel('U,V');

box(axes1,'on');
% Create legend
legend(axes1,'show');

